### PR TITLE
Testing functional tests with upgrade

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-55546

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test:acceptance

**Comment by koor4356** [comment]
ci:retest:acceptance

**Comment by vicnate5** [comment]
ci:stop

**Comment by vicnate5** [comment]
sent fix at https://github.com/koor4356/liferay-portal/pull/63

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
