### PR TITLE
LPS-60244 ant format-source

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by koor4356** [comment]
Thank you, @jbalsas. I will monitor this.

**Comment by jbalsas** [comment]
Hey @koor4356, not sure what this means... maybe your master is in a weird state?

**Comment by koor4356** [comment]
@jbalsas I am going to look into this now and I will let know my finding. Thank you.

**Comment by koor4356** [comment]
Hey @jbalsas, I fixed the issue here https://github.com/evannagayama/liferay-portal/pull/590. There was a conflict within wikiPage macro. Thanks!

**Pull request closed without merging**
