### PR TITLE
Test module integration with upgrade

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-55544

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:stop

**Comment by koor4356** [comment]
ci:retest

**Comment by vicnate5** [comment]
@koor4356 https://github.com/koor4356/liferay-portal/pull/56/commits/71e6641bc429b6cafdfe412a6696bebb21aec5f8

**Pull request closed without merging**
