### PR TITLE
LRQA-55546 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Fixed the issue https://github.com/koor4356/liferay-portal/pull/62. What is the hash used to create the sql dump? you need to use that when running the CI test to prevent problems

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:nocompile

**Comment by vicnate5** [comment]
@koor4356 when dumping the database, you will need to use the following arguments so that it is able to also `create` and `use` the database schema:
```
mysqldump --add-drop-database --databases lportal > create-upgraded-data.sql
```
See the new arguments this adds on https://github.com/koor4356/liferay-portal/pull/63/commits/900179594622cf050fa2b1ad1decb278016c9355

**Comment by vicnate5** [comment]
@koor4356 This seems to be working, there were errors on startup, but I expect these are due to the bundle not being the same SHA as the database dump.

In order to avoid issues you need to make sure all of these git SHAs are in the same
1) Master bundle used to upgrade and create the database dump (Bundle must be DXP profile)
2) This git branch base SHA
3) ci: test: SHA

**Comment by koor4356** [comment]
https://github.com/koor4356/liferay-portal/pull/64

**Pull request closed without merging**
