### PR TITLE
LPS-133825 When DB Partition is enabled we must return the current schema when executing getCatalog

### PR DESCRIPTION
**Pull request by achaparro**
Hi @koor4356,

can you verify if this solves the issue?

Thanks.

cc/@vicnate5

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@achaparro @vicnate5,  looks good. No unique failures. Also, I have downloaded the bundle on this pull request and run an upgrade on it. Upgrade was successful. No error found. All data were correctly upgraded. 

Thanks!

**Comment by achaparro** [comment]
great @koor4356 !

I will repeat the relevant tests since it seems it is not related.

Thanks!

**Comment by achaparro** [comment]
ci:forward

**Comment by achaparro** [comment]
I am going to test it in my repo

@vicnate5 
@koor4356

**Pull request closed without merging**
