### PR TITLE
Testing functional tests with upgrade

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-55546

### CODE REVIEW

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:test

**Comment by koor4356** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 `project.dir` is a real property required by many of our ant scripts to give the base file path, I would not recommend overriding it.

Overall, you are changing far too many things. you only need to change the final SQL file reference used by the tests.

Here is a something to get you started: https://github.com/koor4356/liferay-portal/pull/61

Make sure you are extracting out some of this ant logic and finding a way to test this locally, it will be much easier to debug running locally.

Also, when testing this on CI, please modify test.properties to reduce load. We are using 300-400 servers here without knowing this even works. Please reduce this to 1 functional test until you know this works.

**Pull request closed without merging**
